version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: prakhars962/al-folio:v1.0.0
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
